# Generated by Django 4.2.3 on 2023-07-17 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emp',
            old_name='adress',
            new_name='address',
        ),
    ]
